// Per-icon imports keep the bundle small: the `lucide-react-native` barrel pulls all
// 1800+ icons in because Metro does not tree-shake it. The local IconProps alias also
// keeps tsc from walking lucide's deep generic types at every usage site.
import type { ComponentType } from 'react';
import type { ColorValue, StyleProp, ViewStyle } from 'react-native';

export type IconProps = {
  size?: number;
  color?: ColorValue;
  strokeWidth?: number;
  style?: StyleProp<ViewStyle>;
};

import ArchiveIcon from 'lucide-react-native/icons/archive';
import ArrowRightIcon from 'lucide-react-native/icons/arrow-right';
import AwardIcon from 'lucide-react-native/icons/award';
import BrainIcon from 'lucide-react-native/icons/brain';
import BrainCircuitIcon from 'lucide-react-native/icons/brain-circuit';
import CalendarIcon from 'lucide-react-native/icons/calendar';
import CheckIcon from 'lucide-react-native/icons/check';
import CheckCircle2Icon from 'lucide-react-native/icons/circle-check';
import ClockIcon from 'lucide-react-native/icons/clock';
import CloudSunIcon from 'lucide-react-native/icons/cloud-sun';
import CompassIcon from 'lucide-react-native/icons/compass';
import CpuIcon from 'lucide-react-native/icons/cpu';
import CrownIcon from 'lucide-react-native/icons/crown';
import DatabaseIcon from 'lucide-react-native/icons/database';
import DownloadIcon from 'lucide-react-native/icons/download';
import EyeIcon from 'lucide-react-native/icons/eye';
import FileTextIcon from 'lucide-react-native/icons/file-text';
import GlobeIcon from 'lucide-react-native/icons/globe';
import ImageIcon from 'lucide-react-native/icons/image';
import LaptopIcon from 'lucide-react-native/icons/laptop';
import LayersIcon from 'lucide-react-native/icons/layers';
import LayoutTemplateIcon from 'lucide-react-native/icons/layout-template';
import LeafIcon from 'lucide-react-native/icons/leaf';
import MailIcon from 'lucide-react-native/icons/mail';
import MapPinIcon from 'lucide-react-native/icons/map-pin';
import MenuIcon from 'lucide-react-native/icons/menu';
import MessageSquareIcon from 'lucide-react-native/icons/message-square';
import NewspaperIcon from 'lucide-react-native/icons/newspaper';
import OrbitIcon from 'lucide-react-native/icons/orbit';
import RadioIcon from 'lucide-react-native/icons/radio';
import RocketIcon from 'lucide-react-native/icons/rocket';
import SatelliteIcon from 'lucide-react-native/icons/satellite';
import SearchIcon from 'lucide-react-native/icons/search';
import SendIcon from 'lucide-react-native/icons/send';
import Share2Icon from 'lucide-react-native/icons/share-2';
import ShieldIcon from 'lucide-react-native/icons/shield';
import ShieldCheckIcon from 'lucide-react-native/icons/shield-check';
import SparklesIcon from 'lucide-react-native/icons/sparkles';
import TerminalSquareIcon from 'lucide-react-native/icons/square-terminal';
import TrophyIcon from 'lucide-react-native/icons/trophy';
import UserIcon from 'lucide-react-native/icons/user';
import UsersIcon from 'lucide-react-native/icons/users';
import XIcon from 'lucide-react-native/icons/x';
import ZapIcon from 'lucide-react-native/icons/zap';

export const Archive = ArchiveIcon as unknown as ComponentType<IconProps>;
export const ArrowRight = ArrowRightIcon as unknown as ComponentType<IconProps>;
export const Award = AwardIcon as unknown as ComponentType<IconProps>;
export const Brain = BrainIcon as unknown as ComponentType<IconProps>;
export const BrainCircuit = BrainCircuitIcon as unknown as ComponentType<IconProps>;
export const Calendar = CalendarIcon as unknown as ComponentType<IconProps>;
export const Check = CheckIcon as unknown as ComponentType<IconProps>;
export const CheckCircle2 = CheckCircle2Icon as unknown as ComponentType<IconProps>;
export const Clock = ClockIcon as unknown as ComponentType<IconProps>;
export const CloudSun = CloudSunIcon as unknown as ComponentType<IconProps>;
export const Compass = CompassIcon as unknown as ComponentType<IconProps>;
export const Cpu = CpuIcon as unknown as ComponentType<IconProps>;
export const Crown = CrownIcon as unknown as ComponentType<IconProps>;
export const Database = DatabaseIcon as unknown as ComponentType<IconProps>;
export const Download = DownloadIcon as unknown as ComponentType<IconProps>;
export const Eye = EyeIcon as unknown as ComponentType<IconProps>;
export const FileText = FileTextIcon as unknown as ComponentType<IconProps>;
export const Globe = GlobeIcon as unknown as ComponentType<IconProps>;
export const Image = ImageIcon as unknown as ComponentType<IconProps>;
export const Laptop = LaptopIcon as unknown as ComponentType<IconProps>;
export const Layers = LayersIcon as unknown as ComponentType<IconProps>;
export const LayoutTemplate = LayoutTemplateIcon as unknown as ComponentType<IconProps>;
export const Leaf = LeafIcon as unknown as ComponentType<IconProps>;
export const Mail = MailIcon as unknown as ComponentType<IconProps>;
export const MapPin = MapPinIcon as unknown as ComponentType<IconProps>;
export const Menu = MenuIcon as unknown as ComponentType<IconProps>;
export const MessageSquare = MessageSquareIcon as unknown as ComponentType<IconProps>;
export const Newspaper = NewspaperIcon as unknown as ComponentType<IconProps>;
export const Orbit = OrbitIcon as unknown as ComponentType<IconProps>;
export const Radio = RadioIcon as unknown as ComponentType<IconProps>;
export const Rocket = RocketIcon as unknown as ComponentType<IconProps>;
export const Satellite = SatelliteIcon as unknown as ComponentType<IconProps>;
export const Search = SearchIcon as unknown as ComponentType<IconProps>;
export const Send = SendIcon as unknown as ComponentType<IconProps>;
export const Share2 = Share2Icon as unknown as ComponentType<IconProps>;
export const Shield = ShieldIcon as unknown as ComponentType<IconProps>;
export const ShieldCheck = ShieldCheckIcon as unknown as ComponentType<IconProps>;
export const Sparkles = SparklesIcon as unknown as ComponentType<IconProps>;
export const TerminalSquare = TerminalSquareIcon as unknown as ComponentType<IconProps>;
export const Trophy = TrophyIcon as unknown as ComponentType<IconProps>;
export const User = UserIcon as unknown as ComponentType<IconProps>;
export const Users = UsersIcon as unknown as ComponentType<IconProps>;
export const X = XIcon as unknown as ComponentType<IconProps>;
export const Zap = ZapIcon as unknown as ComponentType<IconProps>;
